### ISSUE TITLE
Change the version of mathcomp in metadata?

### ISSUE THREAD

**Issue by Yosuke-Ito-345** [Yosuke-Ito-345/Actuary#9]
@palmskog 
I have checked that the current theory of Actuary is compatible with the latest CoqPlatform 2024.10.
According to [README](https://github.com/coq/platform/blob/2024.10.0/doc/README~8.19~2024.10.md), the mathcomp version included in CoqPlatform 2024.10 seems to be 2.2.0.
Should I change the Requirements from "Mathematical Components 1.17.0 or 1.18.0" to "Mathematical Components 1.17.0 or later"?
I hope you would correct me if I misunderstand something.

**Comment by palmskog** [comment]
@Yosuke-Ito-345 as far as I can tell, the project is not compatible with MathComp 2.0 or later, regardless of Coq version:
```
File "./theories/Basics.v", line 128, characters 37-49:
Error:
The term "Rplus_assoc'" has type
 "forall r1 r2 r3 : R, r1 + (r2 + r3) = r1 + r2 + r3"
while it is expected to have type "Type".
```

Since there seemingly won't be any MathComp 1.X release beyond 1.19.0, you could for example say that your project is compatible with MathComp 1.17.0 to 1.19.0.

**Comment by Yosuke-Ito-345** [comment]
@palmskog 
Thank you very much for the quick response and pointing my misunderstanding.
I thought the latest CoqPlatform adopts MathComp 2.2.0 due to the following description.

> coq-mathcomp-algebra.2.2.0 (2.2.0) Mathematical Components Library on Algebra

I added MathComp 1.19.0 to the Requirements.
